//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MemberCommunityChat
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string ImageURL { get; set; }
    public string Program { get; set; }
    public System.DateTime Time { get; set; }
    public string Comment { get; set; }
    public int Catergory { get; set; }
}

public partial class MemberEmail
{
    public int EmailId { get; set; }
    public int MemberId { get; set; }
    public string EmailAddress { get; set; }
    public int EmailType { get; set; }
    public string Title { get; set; }
    public string Content1 { get; set; }
    public string Content2 { get; set; }
    public string Content3 { get; set; }
    public string Content4 { get; set; }
    public string Content5 { get; set; }
    public int Status { get; set; }
}

public partial class MemberExercisePlan
{
    public int Id { get; set; }
    public int MemberId { get; set; }
    public int ExercisePlanId { get; set; }
    public string Status { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<decimal> StartWeight { get; set; }
    public Nullable<decimal> StartWaist { get; set; }
    public Nullable<decimal> StartBodyFat { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<decimal> EndWeight { get; set; }
    public Nullable<decimal> EndWaist { get; set; }
    public Nullable<decimal> EndBodyFat { get; set; }
}

public partial class MemberExercisePlanWeek
{
    public int Id { get; set; }
    public int MemberId { get; set; }
    public int MemberExercisePlanId { get; set; }
    public string Status { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public int ExercisePlanWeekId { get; set; }
    public int Week { get; set; }
}

public partial class MemberFoodPlanWeek
{
    public int Id { get; set; }
    public int MemberId { get; set; }
    public int MemberExercisePlanId { get; set; }
    public string Food1 { get; set; }
    public string Food2 { get; set; }
    public string Food3 { get; set; }
    public string Food4 { get; set; }
    public string Food5 { get; set; }
    public string Description { get; set; }
    public int StartWeek { get; set; }
    public int EndWeek { get; set; }
}

public partial class MemberPlanWeekResult
{
    public int Id { get; set; }
    public Nullable<int> MemberId { get; set; }
    public Nullable<int> MemberExercisePlanWeekId { get; set; }
    public Nullable<decimal> StartWeight { get; set; }
    public Nullable<decimal> StartWaist { get; set; }
    public Nullable<decimal> StartBodyFat { get; set; }
    public Nullable<decimal> StartHip { get; set; }
    public Nullable<decimal> StartChest { get; set; }
    public Nullable<decimal> StartHeartRate { get; set; }
    public Nullable<decimal> EndWeight { get; set; }
    public Nullable<decimal> EndWaist { get; set; }
    public Nullable<decimal> EndBodyFat { get; set; }
    public Nullable<decimal> EndHip { get; set; }
    public Nullable<decimal> EndChest { get; set; }
    public Nullable<decimal> EndHeartRate { get; set; }
    public string Questions { get; set; }
    public string FrontPhoto { get; set; }
    public string SidePhoto { get; set; }
    public string BackPhoto { get; set; }
    public string Tasks { get; set; }
}

public partial class PrizeErrorLog
{
    public int Id { get; set; }
    public int MemberId { get; set; }
    public Nullable<int> MemberExercisePlanId { get; set; }
    public System.DateTime LogDate { get; set; }
    public int ErrorLevel { get; set; }
    public string Page { get; set; }
    public string Event { get; set; }
    public string Error { get; set; }
    public string InnerError { get; set; }
}

public partial class PrizeExerciseDayGroupName
{
    public int Id { get; set; }
    public string DayGroupName { get; set; }
}

public partial class PrizeExerciseDayType
{
    public int Id { get; set; }
    public string DayTypeName { get; set; }
    public string Image { get; set; }
}

public partial class PrizeExercisePlan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizeExercisePlan()
    {
        this.PrizeExercisePlanWeeks = new HashSet<PrizeExercisePlanWeek>();
    }

    public int Id { get; set; }
    public string PlanName { get; set; }
    public string Description { get; set; }
    public int ProgramId { get; set; }
    public int LocationId { get; set; }
    public int ExperienceId { get; set; }
    public int LevelId { get; set; }
    public Nullable<int> childPlanId { get; set; }
    public double Price { get; set; }
    public int IsTrialPlan { get; set; }

    public virtual PrizePlanProgram PrizePlanProgram { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeExercisePlanWeek> PrizeExercisePlanWeeks { get; set; }
}

public partial class PrizeExercisePlanWeek
{
    public int Id { get; set; }
    public int ExercisePlanId { get; set; }
    public Nullable<int> FoodPlanId { get; set; }
    public int StartWeek { get; set; }
    public int EndWeek { get; set; }
    public string ExerciseDay1 { get; set; }
    public string ExerciseDay2 { get; set; }
    public string ExerciseDay3 { get; set; }
    public string ExerciseDay4 { get; set; }
    public string ExerciseDay5 { get; set; }
    public string ExerciseDay6 { get; set; }
    public string ExerciseDay7 { get; set; }
    public string Description { get; set; }

    public virtual PrizeExercisePlan PrizeExercisePlan { get; set; }
    public virtual PrizeFoodPlan PrizeFoodPlan { get; set; }
}

public partial class PrizeExercisePlanWeekDay
{
    public int Id { get; set; }
    public int ExercisePlanWeekId { get; set; }
    public int Day { get; set; }
    public int DayTypeId { get; set; }
}

public partial class PrizeExerciseUnit
{
    public int Id { get; set; }
    public string Exercise { get; set; }
    public string AlternateExercise { get; set; }
    public string Reps { get; set; }
    public string Rest { get; set; }
    public string Weight { get; set; }
    public string Comments { get; set; }
    public Nullable<int> UnitOrder { get; set; }
    public string Tempo { get; set; }
    public string Trainning_Set { get; set; }
    public string Image { get; set; }
    public string Video { get; set; }
    public int TimeDuration { get; set; }
}

public partial class PrizeExerciseUnitSet
{
    public int Id { get; set; }
    public int ExerciseUnitId { get; set; }
    public string Sequence { get; set; }
    public int UnitSetId { get; set; }
}

public partial class PrizeExerciseUnitSetForDay
{
    public int Id { get; set; }
    public int ExercisePlanWeekId { get; set; }
    public int ExerciseDay { get; set; }
    public int DayGroupNameId { get; set; }
    public int ExerciseUnitSetId { get; set; }
}

public partial class PrizeFoodPlan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizeFoodPlan()
    {
        this.PrizeExercisePlanWeeks = new HashSet<PrizeExercisePlanWeek>();
    }

    public int Id { get; set; }
    public string PlanName { get; set; }
    public string Description { get; set; }
    public string FoodDay1 { get; set; }
    public string FoodDay2 { get; set; }
    public string FoodDay3 { get; set; }
    public string FoodDay4 { get; set; }
    public string FoodDay5 { get; set; }
    public string FoodDay6 { get; set; }
    public string FoodDay7 { get; set; }
    public string Weeks { get; set; }
    public Nullable<int> ProgramId { get; set; }
    public Nullable<int> LocationId { get; set; }
    public Nullable<int> ExperienceId { get; set; }
    public Nullable<int> LevelId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeExercisePlanWeek> PrizeExercisePlanWeeks { get; set; }
}

public partial class PrizeMember
{
    public int UmbracoId { get; set; }
    public string Firstname { get; set; }
    public string Surname { get; set; }
    public Nullable<System.DateTime> DoB { get; set; }
    public string Gender { get; set; }
    public string Country { get; set; }
    public string Email { get; set; }
    public string StreetAddress { get; set; }
    public string Suburb { get; set; }
    public string City { get; set; }
    public string Postcode { get; set; }
    public string State { get; set; }
    public Nullable<decimal> Height { get; set; }
    public Nullable<decimal> Weight { get; set; }
    public string Password { get; set; }
    public Nullable<decimal> Waist { get; set; }
    public Nullable<decimal> BodyFat { get; set; }
    public string GoalDescription { get; set; }
    public Nullable<decimal> GoalWeight { get; set; }
    public Nullable<decimal> GoalWaist { get; set; }
    public Nullable<decimal> GoalBodyFat { get; set; }
    public string Photo { get; set; }
    public string Mobile { get; set; }
    public string Phone { get; set; }
    public string Twiter { get; set; }
    public string Facebook { get; set; }
    public string Instagram { get; set; }
    public string WhyDIYPT { get; set; }
    public string Questions { get; set; }
    public Nullable<System.DateTime> RegisterDateTime { get; set; }
    public string UserSettings { get; set; }
}

public partial class PrizeMemberLog
{
    public int Id { get; set; }
    public int MemberId { get; set; }
    public Nullable<int> MemberExercisePlanId { get; set; }
    public System.DateTime LogDate { get; set; }
    public string Page { get; set; }
    public string Event { get; set; }
    public string Error { get; set; }
}

public partial class PrizeOrder
{
    public int OrderId { get; set; }
    public System.DateTime OrderDate { get; set; }
    public string Username { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public decimal Total { get; set; }
    public string PaymentTransactionId { get; set; }
    public Nullable<int> MemberPlanId { get; set; }
    public int ExercisePlanId { get; set; }
    public System.DateTime StartDate { get; set; }
}

public partial class PrizePlanExperience
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizePlanLevel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizePlanLocation
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }
}

public partial class PrizePlanProgram
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PrizePlanProgram()
    {
        this.PrizeExercisePlans = new HashSet<PrizeExercisePlan>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Sequence { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PrizeExercisePlan> PrizeExercisePlans { get; set; }
}

public partial class PrizePollingTask
{
    public int Id { get; set; }
    public System.DateTime TaskDate { get; set; }
    public int TaskType { get; set; }
    public int Count { get; set; }
    public string Status { get; set; }
}

public partial class PrizeSysConfig
{
    public int Id { get; set; }
    public Nullable<System.DateTime> SystemDate { get; set; }
}
